// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('../eventmath2026/runtime/eventmath-runtime.js');

const __weights = {};
const __assumptions = [];

const __emMachine = require('../eventmath2026/runtime/eventmath-machine-runtime.js');

let api_port = null;

// star (constant): api port
api_port = 3001;

require('node:http').createServer(async function(req, res) {
  var _method = req.method.toLowerCase();
  var _path = require('node:url').parse(req.url).pathname;
  if (_method === "get" && _path === "/api/groups") {
    // spawn: node /e/summarizer/scanner.js
    groups = await __emMachine.spawnProcess("node /e/summarizer/scanner.js");
    
    res.writeHead(200, {'Content-Type': 'application/json'});
    res.end(JSON.stringify(groups));
    return;
  }
  if (_method === "get" && _path === "/api/health") {
    // spawn: node -e console.log(JSON.stringify({running:true,version:'1.0'}))
    info = await __emMachine.spawnProcess("node -e console.log(JSON.stringify({running:true,version:'1.0'}))");
    
    res.writeHead(200, {'Content-Type': 'application/json'});
    res.end(JSON.stringify(info));
    return;
  }
  res.writeHead(404); res.end('Not found');
}).listen(api_port, function() {
  console.log('EventMath: serving on port ' + api_port);
});