// Generated by EventMath Compiler v0.4
// Runtime: <script src="eventmath-runtime.js"></script>

const EM = typeof EventMathRuntime !== 'undefined'
  ? EventMathRuntime
  : require('..\eventmath2026\runtime\eventmath-runtime.js');

const __weights = {};
const __assumptions = [];

let port = null;
let groups = null;

// star (constant): port
port = 3001;

// rain: groups
groups = null;

require('node:http').createServer(async function(req, res) {
  var _method = req.method.toLowerCase();
  var _path = require('node:url').parse(req.url).pathname;
  if (_method === "get" && _path === "/api/groups") {
    // spawn: node /e/summarizer/scanner.js
    groups = await __emMachine.spawnProcess("node /e/summarizer/scanner.js");
    
    res.writeHead(200, {'Content-Type': 'application/json'});
    res.end(JSON.stringify(groups));
    return;
  }
  if (_method === "get" && _path === "/api/health") {
    // spawn: node -e console.log(JSON.stringify({ok:true,version:'1.0'}))
    health = await __emMachine.spawnProcess("node -e console.log(JSON.stringify({ok:true,version:'1.0'}))");
    
    res.writeHead(200, {'Content-Type': 'application/json'});
    res.end(JSON.stringify(health));
    return;
  }
  if (_method === "post" && _path === "/api/delete") {
    res.writeHead(200, {'Content-Type': 'application/json'});
    res.end(JSON.stringify(_ok_true_message_use_startjs_wrapper_for_file_operations_));
    return;
  }
  if (_method === "post" && _path === "/api/delete-group") {
    res.writeHead(200, {'Content-Type': 'application/json'});
    res.end(JSON.stringify(_ok_true_message_use_startjs_wrapper_for_file_operations_));
    return;
  }
  res.writeHead(404); res.end('Not found');
}).listen(3000, function() {
  console.log('EventMath: serving on port 3000');
});